"""
DAG Factory Sustained Load Test - YAML-based DAG Generation

Dynamically loads all set config files (dag_factory_config_sustained_set_*.yaml)
and generates DAGs from each. Supports multiple sets running in parallel.

Generated by: generate_dag_factory_sustained.py --sets N
Task functions: performance_test_tasks_real.py

Note: This uses dag-factory 1.0+ API which is compatible with Airflow 3.
"""

from dagfactory import load_yaml_dags
import glob
import os

# Discover all set config files
config_dir = os.path.dirname(__file__)
config_pattern = os.path.join(config_dir, "dag_factory_config_sustained_set_*.yaml")
config_files = sorted(glob.glob(config_pattern))

if not config_files:
    raise FileNotFoundError(
        f"No config files found matching {config_pattern}. "
        "Run: python generate_dag_factory_sustained.py --sets N"
    )

# Load DAGs from each set config
for config_file in config_files:
    load_yaml_dags(config_filepath=config_file, globals_dict=globals())
