"""
DAG Factory Concurrent Real Load Test - YAML-based DAG Generation

Uses dag-factory 1.0+ to generate DAGs with REAL concurrent tasks.
ALL DAGs start simultaneously for TRUE concurrent load testing.

Configuration:
- Generated by: generate_dag_factory_config_real.py --tasks <N>
- Default: 65 DAGs × 31 tasks = 2015 actual task instances
- Task duration: 2 minutes
- NO wave delays - all start at once

Configuration file: dag_factory_config_concurrent_real.yaml
Task functions: performance_test_tasks_real.py

Note: This uses dag-factory 1.0+ API which is compatible with Airflow 3.
"""

from dagfactory import load_yaml_dags
import os

# Path to YAML configuration file
config_file = os.path.join(os.path.dirname(__file__), "dag_factory_config_concurrent_real.yaml")

# Generate DAGs from YAML configuration using dag-factory 1.0+ API
# This automatically loads all 100 DAGs defined in the YAML file
load_yaml_dags(config_filepath=config_file, globals_dict=globals())
