"""
DAG Factory Sustained Load Test - YAML-based DAG Generation

Uses dag-factory 1.0+ to generate DAGs for sustained load testing.
Gradual ramp-up, sustained peak load, and gradual ramp-down.

Test Pattern (40 minutes total):
- 0-5 min: Ramp up from 500 → peak tasks
- 5-25 min: Sustain peak load (20 minutes)
- 25-40 min: Ramp down peak → 0 tasks

Configuration:
- Generated by: generate_dag_factory_sustained.py --peak-tasks <N>
- Default: 2000 peak tasks, 20 minute peak duration
- Task duration: 20 minutes (long-running for sustained test)

Configuration file: dag_factory_config_sustained.yaml
Task functions: performance_test_tasks_real.py

Note: This uses dag-factory 1.0+ API which is compatible with Airflow 3.
"""

from dagfactory import load_yaml_dags
import os

# Path to YAML configuration file
config_file = os.path.join(os.path.dirname(__file__), "dag_factory_config_sustained.yaml")

# Generate DAGs from YAML configuration using dag-factory 1.0+ API
load_yaml_dags(config_filepath=config_file, globals_dict=globals())
